### ISSUE TITLE
Add support for internationalization (i18n)

### ISSUE THREAD

**Issue by SKPG-Tech** [pewpewlive/PewPew-Mesh-Studio#17]
Make use of the GetText.NET package to add support for translating the application into multiple languages.

**Comment by Tasty-Kiwi** [comment]
Almost all strings have been internationalized
Afterwards I'll post translatable strings.

**Comment by Tasty-Kiwi** [comment]
Created a repository for i18n: https://github.com/pewpewlive/Mesh-Studio-i18n
